'use client';

import { useState } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';

interface ReportSection {
	[key: string]: string;
}

interface ReportData {
	metadata: {
		ticker: string;
		form: string;
		filed: string;
		generatedAt: string;
	};
	sections: ReportSection;
	data: any;
}

export default function ReportPage() {
	const { data: session, status } = useSession();
	const router = useRouter();

	const [ticker, setTicker] = useState('AAPL');
	const [form, setForm] = useState('10-K');
	const [year, setYear] = useState(2024);
	const [filedDate, setFiledDate] = useState('2024-11-01');
	const [loading, setLoading] = useState(false);
	const [report, setReport] = useState<ReportData | null>(null);
	const [error, setError] = useState<string | null>(null);
	const [exportFormat, setExportFormat] = useState<'markdown' | 'json'>('markdown');

	// Redirect if not authenticated
	if (status === 'loading') {
		return <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-gray-900 to-gray-800 text-white">Loading...</div>;
	}

	if (status === 'unauthenticated') {
		router.push('/login');
		return null;
	}

	const handleGenerateReport = async () => {
		setLoading(true);
		setError(null);
		setReport(null);

		try {
			const res = await fetch(`/api/report/generate?ticker=${ticker}&form=${form}&filed=${filedDate}`);
			
			if (!res.ok) {
				const errorData = await res.json();
				throw new Error(errorData.error || 'Failed to generate report');
			}

			const reportData = await res.json();
			setReport(reportData);
		} catch (err: any) {
			setError(err?.message || 'Failed to generate report');
		} finally {
			setLoading(false);
		}
	};

	const handleExport = () => {
		if (!report) return;

		if (exportFormat === 'markdown') {
			const markdown = generateMarkdownReport(report);
			const blob = new Blob([markdown], { type: 'text/markdown' });
			const url = URL.createObjectURL(blob);
			const a = document.createElement('a');
			a.href = url;
			a.download = `${report.metadata.ticker}_Equity_Report_${report.metadata.filed}.md`;
			document.body.appendChild(a);
			a.click();
			document.body.removeChild(a);
			URL.revokeObjectURL(url);
		} else {
			const json = JSON.stringify(report, null, 2);
			const blob = new Blob([json], { type: 'application/json' });
			const url = URL.createObjectURL(blob);
			const a = document.createElement('a');
			a.href = url;
			a.download = `${report.metadata.ticker}_Equity_Report_${report.metadata.filed}.json`;
			document.body.appendChild(a);
			a.click();
			document.body.removeChild(a);
			URL.revokeObjectURL(url);
		}
	};

	const generateMarkdownReport = (report: ReportData): string => {
		const { metadata, sections } = report;
		
		return `# Equity Research Report: ${metadata.ticker}

**Generated:** ${new Date(metadata.generatedAt).toLocaleString()}  
**Filing:** ${metadata.form} | **Filed Date:** ${metadata.filed}

---

${sections.executive_summary || ''}

---

${sections.business_overview || ''}

---

${sections.valuation || ''}

---

${sections.bull_bear || ''}

---

${sections.catalysts_risks || ''}

---

${sections.analyst_commentary || ''}

---

## Appendix

**Report Metadata:**
- Ticker: ${metadata.ticker}
- Form Type: ${metadata.form}
- Filed Date: ${metadata.filed}
- Generated At: ${metadata.generatedAt}

*This report was automatically generated by EquiSynth Report Composer Agent.*
`;
	};

	return (
		<div className="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900 text-white p-8">
			<div className="max-w-7xl mx-auto">
				{/* Header */}
				<div className="mb-8">
					<h1 className="text-4xl font-bold mb-2">📄 Report Composer Agent</h1>
					<p className="text-gray-300">
						Generate comprehensive equity research reports from all agent analyses
					</p>
				</div>

				{/* Input Form */}
				<div className="bg-white/10 backdrop-blur-md rounded-2xl p-8 mb-8">
					<h2 className="text-2xl font-bold mb-6">Report Parameters</h2>
					
					<div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
						<div>
							<label className="block text-sm font-medium text-gray-300 mb-2">
								Ticker Symbol
							</label>
							<input
								type="text"
								value={ticker}
								onChange={(e) => setTicker(e.target.value.toUpperCase())}
								className="w-full px-4 py-2 bg-white/20 border border-white/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
								placeholder="AAPL"
							/>
						</div>

						<div>
							<label className="block text-sm font-medium text-gray-300 mb-2">
								Form Type
							</label>
							<select
								value={form}
								onChange={(e) => setForm(e.target.value)}
								className="w-full px-4 py-2 bg-white/20 border border-white/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
							>
								<option value="10-K">10-K (Annual Report)</option>
								<option value="10-Q">10-Q (Quarterly Report)</option>
							</select>
						</div>

						<div>
							<label className="block text-sm font-medium text-gray-300 mb-2">
								Year
							</label>
							<input
								type="number"
								value={year}
								onChange={(e) => setYear(parseInt(e.target.value))}
								className="w-full px-4 py-2 bg-white/20 border border-white/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
								placeholder="2024"
							/>
						</div>

						<div>
							<label className="block text-sm font-medium text-gray-300 mb-2">
								Filed Date
							</label>
							<input
								type="date"
								value={filedDate}
								onChange={(e) => setFiledDate(e.target.value)}
								className="w-full px-4 py-2 bg-white/20 border border-white/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
							/>
						</div>
					</div>

					<button
						onClick={handleGenerateReport}
						disabled={loading}
						className="w-full px-6 py-3 bg-gradient-to-r from-purple-500 to-pink-500 text-white font-semibold rounded-lg hover:from-purple-600 hover:to-pink-600 transition disabled:opacity-50 disabled:cursor-not-allowed"
					>
						{loading ? '🔄 Generating Report...' : '🚀 Generate Equity Research Report'}
					</button>

					{error && (
						<div className="mt-4 bg-red-500/20 border border-red-500 rounded-lg p-4">
							<p className="text-red-200">❌ {error}</p>
						</div>
					)}
				</div>

				{/* Generated Report */}
				{report && (
					<div className="space-y-8">
						{/* Report Header & Export */}
						<div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 flex justify-between items-center">
							<div>
								<h2 className="text-2xl font-bold mb-2">
									Equity Research Report: {report.metadata.ticker}
								</h2>
								<p className="text-gray-300 text-sm">
									Generated: {new Date(report.metadata.generatedAt).toLocaleString()} | 
									Filing: {report.metadata.form} | 
									Filed: {report.metadata.filed}
								</p>
							</div>
							<div className="flex gap-4">
								<select
									value={exportFormat}
									onChange={(e) => setExportFormat(e.target.value as 'markdown' | 'json')}
									className="px-4 py-2 bg-white/20 border border-white/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
								>
									<option value="markdown">Markdown</option>
									<option value="json">JSON</option>
								</select>
								<button
									onClick={handleExport}
									className="px-6 py-2 bg-gradient-to-r from-blue-500 to-cyan-500 text-white font-semibold rounded-lg hover:from-blue-600 hover:to-cyan-600 transition"
								>
									📥 Export Report
								</button>
							</div>
						</div>

						{/* Report Sections */}
						{Object.entries(report.sections).map(([key, content]) => (
							<div
								key={key}
								className="bg-white/10 backdrop-blur-md rounded-2xl p-8"
							>
								<div
									className="markdown-content text-gray-200 leading-relaxed"
									dangerouslySetInnerHTML={{
										__html: content
											.replace(/## (.+)/g, '<h2 class="text-3xl font-bold text-white mt-8 mb-4 border-b border-white/20 pb-2">$1</h2>')
											.replace(/### (.+)/g, '<h3 class="text-2xl font-bold text-purple-300 mt-6 mb-3">$1</h3>')
											.replace(/\*\*(.+?)\*\*/g, '<strong class="text-yellow-300 font-semibold">$1</strong>')
											.replace(/\| (.+) \|/g, '<tr><td class="px-4 py-2">$1</td></tr>')
											.replace(/\n\n/g, '</p><p class="mb-4">')
											.replace(/\n/g, '<br>')
											.replace(/✅/g, '<span class="text-green-400">✅</span>')
											.replace(/⚠️/g, '<span class="text-yellow-400">⚠️</span>')
											.replace(/<table>/g, '<table class="w-full border-collapse border border-white/30 mt-4 mb-4"><thead class="bg-white/10"><tr>')
											.replace(/<\/table>/g, '</thead></table>')
											.replace(/<tr>/g, '<tr class="border-b border-white/20">')
											.replace(/<td>/g, '<td class="px-4 py-2 border border-white/20">'),
									}}
								/>
							</div>
						))}
					</div>
				)}
			</div>
		</div>
	);
}

